// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFoP_0O35ISU3rPEPyF9YxsxyoiNCM38',
    appId: '1:268350971071:web:1e8df3b3d3a45c68d13a0a',
    messagingSenderId: '268350971071',
    projectId: 'auth-6160d',
    authDomain: 'auth-6160d.firebaseapp.com',
    storageBucket: 'auth-6160d.appspot.com',
    measurementId: 'G-4ZS0B9VW9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOeimcC5jKQmKAI7NS9NeYn70bp67f3k',
    appId: '1:268350971071:android:c279cbd53cc0bfdfd13a0a',
    messagingSenderId: '268350971071',
    projectId: 'auth-6160d',
    storageBucket: 'auth-6160d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMcD9hUmQf-Zn9wkByiyntgcpLD73z6gw',
    appId: '1:268350971071:ios:5ddbba014235724dd13a0a',
    messagingSenderId: '268350971071',
    projectId: 'auth-6160d',
    storageBucket: 'auth-6160d.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMcD9hUmQf-Zn9wkByiyntgcpLD73z6gw',
    appId: '1:268350971071:ios:f2ae69da44b0f46bd13a0a',
    messagingSenderId: '268350971071',
    projectId: 'auth-6160d',
    storageBucket: 'auth-6160d.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
